### ISSUE TITLE
p-values seems not accurate

### ISSUE THREAD

**Issue by YungDurum** [gwr3n/pwlf#1]
Dear all,

I don't know if this is the right place to this question, but I did not find any other place to ask.

In my data-analysis I tried to fit linear regressions (±160) to a dataset. I determined the breakpoints of the data with an alternative package (ruptures). Subsequently, I used the pwlf package and the method: .fit_with_break(my_breaks) to determine the slope of the lines. I now wish to determine the p-values of those slopes. For this I tried the method: .p_values(method='linear', step_size=0.0001). I deleted the first value since this corresponds to the Y1 value which I'm not interested in. I am only interested in the p-value of the slope.

The results I know get seems not accurate. Some lines that seem to have a very obvious correlation have a very high p value and some lines that seem very arbitrary have a low p-value. I added a few examples that show the p values and the contributing segment. Does anyone know what is wrong or do I maybe approach this problem in a wrong way? 

In the examples the yellow hover screen show the p-value of the segment on the right and the other attributes of the line.
<img width="295" alt="Schermafbeelding 2021-05-12 om 00 01 31" src="https://user-images.githubusercontent.com/69689923/118262469-3ff47e00-b4b5-11eb-9b33-19d67d00dd1e.png">

<img width="475" alt="Schermafbeelding 2021-05-11 om 19 15 42" src="https://user-images.githubusercontent.com/69689923/118262622-6d412c00-b4b5-11eb-8c94-32f8ae53d79c.png">

**Comment by YungDurum** [comment]
I now also figured out that when I use my_pwlf.beta I get different different values than from my.pwlf.calc_slopes()

**Comment by gwr3n** [comment]
Dear YungDurum, 

are you sure you posted this in the right git repo? 

pwlf is not a package for statistical analysis. It is a package to piecewise linearise first order loss functions, as discussed in https://doi.org/10.1016/j.amc.2014.01.019

You say: "I used the pwlf package and the method: .fit_with_break(my_breaks) to determine the slope of the lines." I am not sure what you are trying to do, but it does not look this is matching the content of this repo. 

Kind regards,

Roberto

**Comment by gwr3n** [comment]
> I now also figured out that when I use my_pwlf.beta I get different different values than from my.pwlf.calc_slopes()

On the basis of this additional post, I do think you are posting this in the wrong repo. pwlf does not feature a function calc_slopes().

**Comment by YungDurum** [comment]
Thanks for the quick reply. I indeed posted it in the wrong repo.
